/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sol/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/events/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put: operations["update_me"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["setup_status"];
        put?: never;
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One app as the dashboard sees it. */
        AppInfo: {
            /** Format: date-time */
            checked_at?: string | null;
            id: string;
            manifest?: null | components["schemas"]["Manifest"];
            status: components["schemas"]["Status"];
        };
        /** @description The envelope every event travels in, from app outbox to Sol to the browser. */
        Envelope: {
            data: unknown;
            /**
             * Format: uuid
             * @description UUIDv7 chosen by the producing app; consumers deduplicate on it.
             */
            id: string;
            /**
             * Format: int64
             * @description Position in the producing app's outbox.
             */
            seq: number;
            /** @description The app that produced it. */
            source: string;
            /** @description What it is about, as `<entity>/<id>`. */
            subject?: string | null;
            /**
             * @description One sentence for people, written by the app: `Did “Walk outside”, 4 days in a row`.
             *     Sol's activity feed and notifications show it as is.
             */
            summary?: string | null;
            /** Format: date-time */
            time: string;
            /** @description `<app>.<entity>.<past-tense verb>`, for example `terra.habit.checked`. */
            type: string;
            /** @description The user the event belongs to; `None` for system-wide events. */
            user?: string | null;
            /**
             * Format: int32
             * @description Version of `data`'s shape for this type.
             */
            v: number;
        };
        /** @description The JSON error body every Sol service returns. */
        ErrorBody: {
            /** @description Stable machine-readable code, e.g. `unauthorized`. */
            error: string;
            message: string;
        };
        EventType: {
            /** @description Sol raises a system notification for it while Sol isn't in front. */
            notify?: boolean;
            type: string;
            /** Format: int32 */
            v: number;
        };
        Events: {
            consumes?: string[];
            emits?: components["schemas"]["EventType"][];
        };
        Item: {
            /** @description Draws a checkbox when set. */
            done?: boolean | null;
            id: string;
            label: string;
            /** @description A short note on the right, e.g. a streak or a time. */
            meta?: string | null;
            toggle?: null | components["schemas"]["Toggle"];
        };
        LoginRequest: {
            password: string;
            username: string;
        };
        /** @description What an app tells Sol about itself at `GET /_sol/manifest`. */
        Manifest: {
            /** Format: int32 */
            contract: number;
            description?: string;
            events?: components["schemas"]["Events"];
            id: string;
            name: string;
            /** @description Serves a web UI at `/ui/`, which Sol shows at `/<id>/`. */
            ui?: boolean;
            version: string;
            widgets?: components["schemas"]["Widget"][];
        };
        /** @description The signed-in person, as the browser sees them. */
        Me: {
            id: string;
            /** @description IANA time zone, e.g. `Europe/Copenhagen`. */
            tz: string;
            username: string;
        };
        Progress: {
            /** Format: double */
            max: number;
            /** Format: double */
            value: number;
        };
        Row: {
            label: string;
            value: string;
        };
        SetupRequest: {
            /** @description The one-time code Sol printed to its log on first start. */
            code: string;
            password: string;
            tz: string;
            username: string;
        };
        SetupStatus: {
            /** @description True until the first account exists. */
            needed: boolean;
        };
        /** @enum {string} */
        Status: "unknown" | "up" | "down";
        /**
         * @description Ticking a checklist item sends `{ "<field>": <new state> }` with `method`
         *     to `path` under the app's API, e.g. `PUT /api/terra/habits/1/today`.
         */
        Toggle: {
            field: string;
            method: string;
            path: string;
        };
        UpdateMe: {
            tz: string;
        };
        /** @description A dashboard widget: an API route that returns a `WidgetView`. */
        Widget: {
            id: string;
            /** @description Path under the app's API, e.g. `/widgets/today` (Sol serves it at `/api/<app>/widgets/today`). */
            path: string;
            /** @description Event types (`*` allowed at the end) that should refresh it. */
            refresh_on?: string[];
            title: string;
        };
        WidgetView: {
            /** @description What the figure counts, e.g. `habits done today`. */
            caption?: string | null;
            /** @description Shown instead when the widget has nothing else to say. */
            empty?: string | null;
            /** @description The headline figure, e.g. `2 / 3`. */
            figure?: string | null;
            /** @description A list, or a checklist when items have `done`. */
            items?: components["schemas"]["Item"][];
            progress?: null | components["schemas"]["Progress"];
            /** @description `Label: value` rows. */
            rows?: components["schemas"]["Row"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppInfo"][];
                };
            };
        };
    };
    recent: {
        parameters: {
            query?: {
                /** @description Only this event type, e.g. `terra.habit.checked`. */
                type?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"][];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMe"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    setup_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
