/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sol/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["add_from_github"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_connections"];
        put?: never;
        post: operations["create_connection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/connections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_connection"];
        options?: never;
        head?: never;
        patch: operations["update_connection"];
        trace?: never;
    };
    "/api/sol/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_devices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/events/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/housekeeping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Runs the daily chores now: writes down when devices were last seen,
         *     clears what has run its course, and makes a backup copy if one is set up.
         */
        post: operations["housekeep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put: operations["update_me"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/pairings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/pairings/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/pairings/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/settings/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["set_github_token"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["setup_status"];
        put?: never;
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/widgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_widgets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/widgets/{world}/{id}/items/{item}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["toggle"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/worlds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_worlds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/worlds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/worlds/{id}/download/{asset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/worlds/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/worlds/{id}/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["install"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/worlds/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["release"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/worlds/{id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["remove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sol/worlds/{id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["settings"];
        put: operations["update_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["changes_since"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/docs/{collection}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_docs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/docs/{collection}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_doc"];
        put: operations["put_doc"];
        post?: never;
        delete: operations["delete_doc"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["emit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["inbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbox/{n}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claim_delivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["device_me"];
        put?: never;
        post?: never;
        delete: operations["unpair_self"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pair/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["device_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/update/download/{asset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["download_update"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/widgets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["push"];
        post?: never;
        delete: operations["remove_widget"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Action: {
            id: string;
            /** @description How the connection builder says it: `Tick a habit`. */
            label: string;
            params?: components["schemas"]["Field"][];
        };
        AddRequest: {
            /** @description `owner/name`, or the repository's GitHub address. */
            repo: string;
        };
        Asset: {
            /** @description Download through Sol: `/api/sol/worlds/<id>/download/<asset id>`. */
            download: string;
            /** Format: int64 */
            id: number;
            name: string;
            /** @description `linux`, `windows`, `macos` or `android`; `None` for other files. */
            platform?: string | null;
            /** Format: int64 */
            size: number;
        };
        /** @description `GET /api/v1/changes?after=N`: every write after version `N`, oldest first. */
        ChangePage: {
            changes: components["schemas"]["Doc"][];
            /** @description More changes are waiting; ask again straight away. */
            more: boolean;
            /**
             * Format: int64
             * @description Send as `after` next time.
             */
            next: number;
        };
        /** @description Sol's answer to an app asking for updates. */
        Check: {
            /** @description The newest version released, when Sol could find out. */
            latest?: string | null;
            /**
             * @description Why there is no offer, for people (no release yet, GitHub unreachable,
             *     no file for this platform, …); `None` when the app is up to date.
             */
            message?: string | null;
            offer?: null | components["schemas"]["Offer"];
        };
        Collection: {
            id: string;
            label: string;
        };
        CollectionCount: {
            /** Format: int64 */
            count: number;
            id: string;
            label: string;
        };
        /** @description The `409` body when `if_version` didn't match. */
        Conflict: {
            current?: null | components["schemas"]["Doc"];
            error: string;
            message: string;
        };
        Connection: {
            /** Format: date-time */
            created_at: string;
            enabled: boolean;
            /**
             * Format: int64
             * @description How many times it has run.
             */
            fired: number;
            id: string;
            /** Format: date-time */
            last_fired?: string | null;
            params: {
                [key: string]: unknown;
            };
            then: components["schemas"]["Then"];
            when: components["schemas"]["When"];
        };
        ConnectionUpdate: {
            enabled: boolean;
        };
        /** @description Something another world asked this one to do, through a connection. */
        Delivery: {
            /** @description One of the world's `actions`, or `widget.toggle` from Sol's dashboard. */
            action: string;
            connection?: string | null;
            /** Format: date-time */
            created_at: string;
            event?: null | components["schemas"]["Envelope"];
            /**
             * Format: int64
             * @description Inbox cursor.
             */
            n: number;
            params: unknown;
        };
        /** @description A paired app, as Sol's UI shows it. */
        DeviceInfo: {
            /** Format: date-time */
            created_at: string;
            id: string;
            /** Format: date-time */
            last_seen?: string | null;
            name: string;
            platform?: string | null;
            /** @description The version of the app it last ran, e.g. `0.2.0`. */
            version?: string | null;
            world: string;
        };
        /** @description `GET /api/v1/me`: who this device is. */
        DeviceMe: {
            device_id: string;
            user: components["schemas"]["Person"];
            world: string;
        };
        Doc: {
            collection: string;
            /** @description `null` for tombstones. */
            data: unknown;
            /** @description A tombstone: the document was deleted at `version`. */
            deleted?: boolean;
            id: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: int64
             * @description Increases with every write in this world; the sync cursor.
             */
            version: number;
        };
        /** @description What a world app posts to `POST /api/v1/events`. */
        Emit: {
            data?: unknown;
            /**
             * Format: uuid
             * @description Optional UUIDv7, so a retried post is stored once.
             */
            id?: string | null;
            subject?: string | null;
            summary?: string | null;
            type: string;
            /** Format: int32 */
            v?: number;
        };
        /** @description An event as Sol stored it. */
        Envelope: {
            data: unknown;
            /**
             * Format: uuid
             * @description UUIDv7; the same id posted twice is stored once.
             */
            id: string;
            /**
             * Format: int64
             * @description Position in Sol's event log.
             */
            seq: number;
            /** @description The world it came from; Sol sets it from the device's pairing. */
            source: string;
            /** @description What it is about, as `<thing>/<id>`. */
            subject?: string | null;
            /** @description One sentence for people: `Did “Walk outside”, 4 days in a row`. */
            summary?: string | null;
            /** Format: date-time */
            time: string;
            /** @description `<world>.<thing>.<past-tense verb>`, for example `terra.habit.checked`. */
            type: string;
            /** @description The person it belongs to; `None` for events about Sol itself. */
            user?: string | null;
            /**
             * Format: int32
             * @description Version of `data`'s shape for this type.
             */
            v: number;
        };
        /** @description The JSON body of every error Sol returns. */
        ErrorBody: {
            /** @description Stable machine-readable code, e.g. `unauthorized` or `conflict`. */
            error: string;
            /** @description A sentence for people. */
            message: string;
        };
        EventKind: {
            /** @description How the connection builder says it: `A habit is ticked`. */
            label: string;
            type: string;
        };
        Export: {
            docs: components["schemas"]["Doc"][];
            /** Format: date-time */
            exported_at: string;
            world: string;
        };
        /** @description A parameter of an action. */
        Field: {
            hint?: string | null;
            key: string;
            kind: components["schemas"]["FieldKind"];
            label: string;
            required?: boolean;
        };
        /** @enum {string} */
        FieldKind: "text" | "url" | "secret" | "number" | "toggle" | "time";
        GithubToken: {
            /** @description A token that can read the worlds' repositories; empty or null removes it. */
            token?: string | null;
        };
        /** @description `GET /_sol/health`. */
        Health: {
            /** @description CPU architecture the binary was built for, e.g. `aarch64`. */
            arch: string;
            db: string;
            /**
             * Format: int32
             * @description The oldest protocol Sol still speaks with apps.
             */
            min_protocol: number;
            /**
             * Format: int32
             * @description The newest protocol Sol speaks with apps.
             */
            protocol: number;
            status: string;
            /** Format: int64 */
            uptime_s: number;
            version: string;
        };
        /** @description `GET /api/v1/inbox?after=N`. */
        InboxPage: {
            deliveries: components["schemas"]["Delivery"][];
            /** Format: int64 */
            next: number;
        };
        Item: {
            /** @description Draws a checkbox when set. */
            done?: boolean | null;
            id: string;
            label: string;
            /** @description A short note on the right, e.g. a streak or a time. */
            meta?: string | null;
            /**
             * @description The box can be ticked from the dashboard. Sol then shows the new state
             *     at once and puts a `widget.toggle` delivery in the world's inbox with
             *     `{ "widget", "item", "done" }`, for the app to apply.
             */
            toggle?: boolean;
        };
        /**
         * @description How a copy of an app was installed, which decides how it updates.
         * @enum {string}
         */
        Kind: "portable" | "setup" | "deb" | "rpm";
        LoginRequest: {
            password: string;
            username: string;
        };
        /** @description The signed-in person, as the browser sees them. */
        Me: {
            id: string;
            /** @description IANA time zone, e.g. `Europe/Copenhagen`. */
            tz: string;
            username: string;
        };
        NewConnection: {
            params?: {
                [key: string]: unknown;
            };
            then_action: string;
            then_world: string;
            /** @description An event type an installed world emits, e.g. `mercury.review.finished`. */
            when: string;
        };
        /** @description A newer version, ready to download through Sol. */
        Offer: {
            /** @description Path on Sol to download it from, with the device's token. */
            download: string;
            /** @description The release file's name. */
            file: string;
            /** @description The release notes, in Markdown. */
            notes?: string | null;
            /** Format: date-time */
            published_at?: string | null;
            /** @description The file's minisign signature, base64 as `tauri signer sign` writes it. */
            signature: string;
            /** Format: int64 */
            size: number;
            version: string;
        };
        PairClaim: {
            id: string;
            secret: string;
        };
        PairRequest: {
            /** @description How the device appears in Sol, e.g. `Desktop` or `Lukas's phone`. */
            device: string;
            /** @description `linux`, `windows`, `macos`, `android` or `ios`. */
            platform?: string | null;
            /** @description The world the app is, e.g. `terra`. */
            world: string;
        };
        PairStarted: {
            /** @description Show this; the person approves the request that carries it. */
            code: string;
            /** Format: date-time */
            expires_at: string;
            id: string;
            /** @description Proves the claim comes from the app that started the pairing. */
            secret: string;
        };
        /** @description Answer to a claim once the person has approved it. */
        Paired: {
            device_id: string;
            /** @description Keep it safe, e.g. in the system keyring; it is shown only once. */
            token: string;
            user: components["schemas"]["Person"];
            world: string;
        };
        /** @description Answer to a claim that is still waiting for the person. */
        Pending: {
            status: string;
        };
        /** @description A request to pair, as Sol's UI shows it. */
        PendingPairing: {
            /** @description The app shows the same code; approve only if they match. */
            code: string;
            /** Format: date-time */
            created_at: string;
            device: string;
            /** Format: date-time */
            expires_at: string;
            id: string;
            platform?: string | null;
            world: string;
        };
        Person: {
            id: string;
            /** @description IANA time zone; "today" in a world means today here. */
            tz: string;
            username: string;
        };
        Progress: {
            /** Format: double */
            max: number;
            /** Format: double */
            value: number;
        };
        /** @description `PUT /api/v1/docs/{collection}/{id}`. */
        Put: {
            data: unknown;
            /**
             * Format: int64
             * @description Write only if the document is still at this version (`0`: only if it
             *     doesn't exist yet). Leave out to always write.
             */
            if_version?: number | null;
        };
        Release: {
            assets: components["schemas"]["Asset"][];
            /** Format: date-time */
            checked_at: string;
            /** @description Why there are no downloads, for people. */
            message?: string | null;
            /** @description The release notes, in Markdown. */
            notes?: string | null;
            /** Format: date-time */
            published_at?: string | null;
            status: components["schemas"]["ReleaseStatus"];
            /** @description The release page on GitHub. */
            url: string;
            version?: string | null;
        };
        /** @enum {string} */
        ReleaseStatus: "ok" | "none" | "unreachable";
        RemoveRequest: {
            /** @description Also delete everything the world keeps in Sol. Can't be undone. */
            delete_data?: boolean;
        };
        Row: {
            label: string;
            value: string;
        };
        Setting: {
            default?: unknown;
            hint?: string | null;
            key: string;
            kind: components["schemas"]["FieldKind"];
            label: string;
            /**
             * @description One value for every world that names the same thing (`navidrome-url`):
             *     set in any of them, Sol keeps it once and hands it to all of them.
             */
            shared?: string | null;
        };
        /** @description A world's setting, as the settings form shows it. */
        SettingView: {
            default?: unknown;
            hint?: string | null;
            key: string;
            kind: components["schemas"]["FieldKind"];
            label: string;
            /** @description A value is stored (the only thing shown for secrets). */
            set: boolean;
            /** @description Other installed worlds that use the same value (a shared setting). */
            shared_with: string[];
            /** @description The stored value; never sent for secrets. */
            value?: unknown;
        };
        /** @description New values by key; `null` goes back to the default. */
        SettingsUpdate: {
            values: {
                [key: string]: unknown;
            };
        };
        SetupRequest: {
            /** @description The one-time code Sol printed to its log on first start. */
            code: string;
            password: string;
            tz: string;
            username: string;
        };
        SetupStatus: {
            /** @description True until the first account exists. */
            needed: boolean;
        };
        /** @description A newer Sol than the one running. */
        SolUpdate: {
            notes?: string | null;
            /** Format: date-time */
            published_at?: string | null;
            /** @description The release page. */
            url: string;
            version: string;
        };
        /**
         * @description A connection a world suggests: "when this happens there, do that here"
         *     (or the other way round). Sol offers it, with `why`, wherever the person
         *     can make it in one click; nothing is connected without them.
         */
        Suggested: {
            /** @description The action's parameters, filled in. */
            params?: {
                [key: string]: unknown;
            };
            /** @description Its action's id. */
            then_action: string;
            /** @description The world whose action runs. */
            then_world: string;
            /** @description The event, e.g. `saturn.title.rated`; its world is the part before the first dot. */
            when: string;
            /** @description One sentence on what it does for the person: `Titan learns what you rate.` */
            why: string;
        };
        SystemInfo: {
            /** @description CPU architecture, e.g. `aarch64` on the NAS. */
            arch: string;
            /** @description Where the daily copies of the databases go, if anywhere. */
            backup_dir?: string | null;
            /**
             * Format: int64
             * @description Bytes on disk: Sol's database and every world's.
             */
            data_bytes: number;
            /** @description Where Sol keeps its data and every world's. */
            data_dir: string;
            /** Format: int64 */
            devices: number;
            /**
             * Format: int64
             * @description Devices seen in the last five minutes.
             */
            devices_online: number;
            /** @description A GitHub token is set (the token itself is never shown). */
            github_token: boolean;
            /**
             * Format: int32
             * @description Events older than this many days are cleared; 0 keeps them all.
             */
            keep_events_days: number;
            /** Format: int64 */
            pending_pairings: number;
            /**
             * Format: int32
             * @description The newest protocol Sol speaks with apps.
             */
            protocol: number;
            public_url?: string | null;
            update?: null | components["schemas"]["SolUpdate"];
            /** Format: int64 */
            uptime_s: number;
            version: string;
            /** Format: int64 */
            worlds: number;
        };
        Then: {
            action: string;
            label: string;
            world: string;
        };
        Tick: {
            done: boolean;
        };
        UpdateMe: {
            tz: string;
        };
        When: {
            label: string;
            type: string;
            world: string;
        };
        Widget: {
            id: string;
            title: string;
            /** Format: date-time */
            updated_at: string;
            view: components["schemas"]["WidgetView"];
            world: string;
        };
        /**
         * @description `PUT /api/v1/widgets/{id}`: the latest look of one of the world's widgets
         *     on Sol's dashboard.
         */
        WidgetPush: {
            title: string;
            view: components["schemas"]["WidgetView"];
        };
        WidgetView: {
            /** @description What the figure counts, e.g. `habits done today`. */
            caption?: string | null;
            /** @description Shown instead when the widget has nothing else to say. */
            empty?: string | null;
            /** @description The headline figure, e.g. `2 / 3`. */
            figure?: string | null;
            /** @description A list, or a checklist when items have `done`. */
            items?: components["schemas"]["Item"][];
            progress?: null | components["schemas"]["Progress"];
            /** @description `Label: value` rows. */
            rows?: components["schemas"]["Row"][];
        };
        WorldDetail: {
            /**
             * Format: int64
             * @description The world's database on disk.
             */
            bytes: number;
            collections: components["schemas"]["CollectionCount"][];
            world: components["schemas"]["WorldSummary"];
        };
        WorldManifest: {
            /** @description Things it can do when another world's event arrives. */
            actions?: components["schemas"]["Action"][];
            /** @description What it keeps in Sol, for the data overview. */
            collections?: components["schemas"]["Collection"][];
            /**
             * @description Connections this world works best with, offered in Sol once both
             *     worlds are installed: a moon lists the ones to and from its planet.
             */
            connections?: components["schemas"]["Suggested"][];
            /** @description Events it posts, which connections can listen for. */
            emits?: components["schemas"]["EventKind"][];
            /** @description Lowercase letters, digits and dashes; also the world's namespace. */
            id: string;
            name: string;
            /** @description The planet a moon belongs to, e.g. `neptune` for Triton. */
            parent?: string | null;
            /** @description `owner/name` on GitHub, where releases and the app downloads live. */
            repo: string;
            /** @description Settings people set once in Sol; every paired device reads them. */
            settings?: components["schemas"]["Setting"][];
            /** @description One line about what it is for. */
            tagline: string;
        };
        /** @description One world as the Worlds page shows it. */
        WorldSummary: {
            /** @description Part of Sol's own catalog, rather than added from GitHub. */
            builtin: boolean;
            /**
             * Format: int64
             * @description Paired devices.
             */
            devices: number;
            installed: boolean;
            /** Format: date-time */
            installed_at?: string | null;
            /**
             * Format: date-time
             * @description When one of its devices last talked to Sol.
             */
            last_seen?: string | null;
            manifest: components["schemas"]["WorldManifest"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    add_from_github: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldSummary"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_connections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"][];
                };
            };
        };
    };
    create_connection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewConnection"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_connection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_connection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_devices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceInfo"][];
                };
            };
        };
    };
    revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    recent: {
        parameters: {
            query?: {
                /** @description Only this event type, e.g. `terra.habit.checked`. */
                type?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"][];
                };
            };
        };
    };
    housekeep: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMe"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    pending: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingPairing"][];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    decline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_github_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GithubToken"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    setup_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
    list_widgets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Widget"][];
                };
            };
        };
    };
    toggle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world: string;
                id: string;
                item: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Tick"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Widget"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_worlds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldSummary"][];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                asset: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file, streamed from GitHub */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A JSON download of everything the world keeps for you */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Export"];
                };
            };
        };
    };
    install: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldSummary"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    release: {
        parameters: {
            query?: {
                /** @description Ask GitHub now instead of using the copy from the last hour. */
                refresh?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Release"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    settings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingView"][];
                };
            };
        };
    };
    update_settings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingView"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    changes_since: {
        parameters: {
            query?: {
                /** @description The `next` of the previous page; 0 for everything. */
                after?: number;
                /** @description Seconds to wait when nothing has changed yet (at most 25). */
                wait?: number;
                /** @description At most this many changes (default and maximum 500). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePage"];
                };
            };
        };
    };
    list_docs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Doc"][];
                };
            };
        };
    };
    get_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Doc"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    put_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Put"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Doc"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conflict"];
                };
            };
        };
    };
    delete_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tombstone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Doc"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    emit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Emit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    inbox: {
        parameters: {
            query?: {
                /** @description The `next` of the previous page; 0 for everything. */
                after?: number;
                /** @description Seconds to wait when nothing is waiting yet (at most 25). */
                wait?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxPage"];
                };
            };
        };
    };
    claim_delivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This device acts on it */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Another device already did */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    device_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceMe"];
                };
            };
        };
    };
    unpair_self: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairStarted"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    claim: {
        parameters: {
            query?: {
                /** @description Seconds to wait for the person to approve (at most 25). */
                wait?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairClaim"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paired"];
                };
            };
            /** @description Not approved yet; ask again */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pending"];
                };
            };
            /** @description Expired, declined or unknown; start again */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    device_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Values with defaults filled in, secrets included */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    check: {
        parameters: {
            query: {
                /** @description The version running now, e.g. `0.1.0`. */
                version: string;
                /** @description See [`target`]. */
                target: string;
                kind: components["schemas"]["Kind"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Check"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    download_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file, streamed from GitHub */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    push: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WidgetPush"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    remove_widget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
